### PR TITLE
Fix NameError and qiniu api response handlings

### PR DESCRIPTION
**Pull request by menghan**

### CODE REVIEW

**Comment by lepture** [comment]
七牛这个 Go style 的 Error handler 好讨厌。

**Comment by lepture** [comment]
@menghan What's your PyPI account?

**Comment by tonyseek** [comment]
:clap:

**Comment by menghan** [comment]
@lepture menghan or menghan412#gmail.com

**Comment by lepture** [comment]
@menghan added you as maintainer

**Pull request merged**
